[package]
name = "rust-tests"
version = "0.1.0"
edition = "2021"

[dependencies]
serde_json = "1.0"
datalogic-rs = "2.1.4"
jsonlogic-rs = "0.4.0"
jsonlogic = "0.5"
serde = { version = "1.0", features = ["derive"] }
